# -*- coding: utf-8 -*-
"""US_Superstore_Data_Clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYwlvFGgV5C_6Q_yl1qsxEZ5xPINytYy
"""

import pandas as pd

df = pd.read_csv('Superstore.csv', encoding='ISO-8859-1')

df.info()

df.describe().transpose()

df.dtypes

df.isnull().sum()

df.duplicated().sum()

